# Copyright (c) 2020-2026 Robert Scheck <robert@fedoraproject.org>
# Copyright (c) 2026 Joshua Sing <joshua@openbsd.org>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

name: "Lint"

on:
  push:
    branches:
      - "master"
      - "[0-9].[0-9]"
      - "[0-9].[0-9]p[0-9]"
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  shellcheck:
    name: "shellcheck"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: "Run shellcheck"
        run: git ls-files -z '*.sh' | xargs -0 -r shellcheck -e SC1091

      - name: "Enforce max 79 characters per line"
        run: |
          wc -L *.sh | sort -nr
          MLL=$(gawk '{ if(length > L) { L=length } } END { print L }' *.sh)
          (( ${MLL:-80} <= 79 )) || exit 1

  hadolint:
    name: "hadolint"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: "Run hadolint"
        uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          dockerfile: Dockerfile
