name: "Trivy"

on:
  schedule:
    - cron: '5 5 * * *'  # 05:05 everyday UTC
  workflow_dispatch:

permissions: {}

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

jobs:
  trivy:
    name: "Trivy"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # needed to upload SARIF
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: "Run Trivy on rpki/rpki-client:latest"
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: rpki/rpki-client:latest
          format: sarif
          output: trivy-results.sarif

      - name: "Upload scan results"
        uses: github/codeql-action/upload-sarif@b96794f015dfd88f77b49b1c93e0fa7110f94c63 # v4.38.0
        with:
          sarif_file: trivy-results.sarif
